# 日志等级
log_level: debug
# 验证码识别 API
ocr_api: https://cocr.xm.mk/
# 资源文件，留空使用本地文件
resources_file: https://file-1257193553.cos.ap-shanghai.myqcloud.com/NUAA-Court-Reservation/resources.json

# 登录信息
auth:
   # 预约系统 Cookie
  cookie: vjuid=xxxxx; vjvd=xxxxxxxxxxxxxxxxx; vt=xxxxx; PHPSESSID=xxxxxx
   # i·南航 APP Token
  access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  refresh_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  username: '011710101'
   # 统一身份认证系统密码
  password: password
  imei:  # 模拟设备信息，应为一个合法的UUID(大写)或留空

# 场地类型
court_id: 19

# 要预约的场地列表
courts_list:
- time: '09:00-10:00'
  courts: [3, 4, 5]

- time: '18:00-19:00'
  courts: [6]

# 通知设置
notify:
  # 微信 Push plus 推送
  PUSH_PLUS_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Bark 推送
  BARK_PUSH':  # Bark IP 或设备码，例：https://api.day.app/DxHcxxxxxRxxxxxxcm/
  # QQ 推送
  CQHTTP_URL:                 # go-cqhttp API
  CQHTTP_MESSAGE_TYPE:        # group：发送到群聊；private：发送到私聊
  CQHTTP_QQ:                  # 群号 / QQ号
  CQHTTP_TOKEN:               # Token
  # Telegram 推送
  TG_BOT_TOKEN:       # Telegram 机器人的 TG_BOT_TOKEN，例：1407203283:AAG9rt-6RDaaX0HBLZQq0laNOh898iFYaRQ
  TG_USER_ID:         # Telegram 机器人的 TG_USER_ID，例：1434078534
  TG_API_HOST:        # Telegram 代理 api