name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  main:
    name: Publish serverless release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Initialization environment
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
      - name: Install requirements
        run: pip install -t . -r ./requirements.txt
      - name: Install zip
        run: |
          sudo -E apt-get update
          sudo -E apt-get install zip
      - name: Pack serverless file
        run: |
          zip -r "Court_Reservation_$RELEASE_VERSION"".zip" . -x "*.pyc" -x "./bin/*" -x "*.so" -x ".git/*" -x ".github/*" -x ".gitignore"
        env: 
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: "*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
